### ISSUE TITLE
Make higher fidelity mockup from the wireframe

### ISSUE THREAD

**Issue by colinloretz** [renocollective/member-portal#134]
![image_uploaded_from_ios_1024](https://user-images.githubusercontent.com/36084/35715606-725afb0e-0788-11e8-937b-ee3bf26dc4b2.jpg)

**Comment by zachlyon** [comment]
@colinloretz - I can work on this.

**Comment by zachlyon** [comment]
@BrendaPenn @colinloretz @joshfleming - Here are some preliminary ideas: https://xd.adobe.com/view/1381ecf3-8ed4-4306-8638-1d434b111bcd/ - you can click thru the views there, PNGs below.

![signinup 2x](https://user-images.githubusercontent.com/6486623/35827626-9749a7da-0a71-11e8-8195-55b30ba7fcab.png)

![home stream 2x](https://user-images.githubusercontent.com/6486623/35827623-9667b852-0a71-11e8-92e4-c7c28e2f2065.png)

![members directory grid 2x](https://user-images.githubusercontent.com/6486623/35827624-9683d564-0a71-11e8-9235-2cbe18ab3f08.png)

![member profile 2x](https://user-images.githubusercontent.com/6486623/35827627-97693514-0a71-11e8-8a78-f957ab6084f5.png)

![handbook 2x](https://user-images.githubusercontent.com/6486623/35827625-96a6ae72-0a71-11e8-8a64-138640bb1420.png)
