### ISSUE TITLE
As a user I want to have a photo on my user profile

### ISSUE THREAD

**Issue by colinloretz** [renocollective/member-portal#2]

**Comment by suetingc** [comment]
https://www.youtube.com/watch?v=WQAR4bPeNCs&list=PL-1Xnch1lKFgxn0phkKuY9f9PGnQUFErp&index=5

use paperclip gem https://github.com/thoughtbot/paperclip

might need image magic

**Comment by elskwid** [comment]
@suetingc you should consider [CarrierWave](https://github.com/carrierwaveuploader/carrierwave). Many codebases made the switch from PaperClip to CW years ago. I don't know what the conventional wisdom is but we've had good luck with CarrierWave.

**Comment by w1zeman1p** [comment]
What about gravatar?

**Comment by suetingc** [comment]
looks like this was resolved in #52
