### ISSUE TITLE
Fix sign in screen bootstrap styling

### ISSUE THREAD

**Issue by colinloretz** [renocollective/member-portal#246]
The image for the sign in screen is bleeding a bit and application.scss has some css in it that is conflicting with some of bootstraps default styling. We should move this to a scss file that is imported in application.scss with the right amount of specificity so it doesn't override existing styles.

Here are some examples from Bootstrap:
http://getbootstrap.com/docs/4.1/examples/sign-in/
http://getbootstrap.com/docs/4.1/examples/cover/

<img width="1204" alt="screen shot 2018-04-11 at 9 54 31 am" src="https://user-images.githubusercontent.com/36084/38631415-8e045032-3d6e-11e8-8d1a-1d78c3d792c4.png">

**Comment by BrendaPenn** [comment]
closed with pr #265
