### ISSUE TITLE
Question: MySQL vs PostgreSQL

### ISSUE THREAD

**Issue by elskwid** [renocollective/member-portal#43]
I noticed that the project is using MySQL currently. Any reason for this choice?

**Comment by colinloretz** [comment]
Nope! We did rails new without any modifiers :)

**Comment by suetingc** [comment]
we'll need to remove once we move to PostgreSQL

  serialize :avatars, JSON # If you use SQLite, add this line.

from the app--> models --> members.rb

**Comment by w1zeman1p** [comment]
+1 for postgres :)

**Comment by colinloretz** [comment]
Closing this question and deferring to issue #54
